// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABJQIwmyCHwbwVTA15T67cZs6aXy4Sa9A',
    appId: '1:545721613351:web:4689c1f338b49deb4d6202',
    messagingSenderId: '545721613351',
    projectId: 'schedule-up-deejyd',
    authDomain: 'schedule-up-deejyd.firebaseapp.com',
    storageBucket: 'schedule-up-deejyd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSMge1lXo7xZc59wnvu_7wRPacdKynVyA',
    appId: '1:545721613351:android:084e54edf9aaa7374d6202',
    messagingSenderId: '545721613351',
    projectId: 'schedule-up-deejyd',
    storageBucket: 'schedule-up-deejyd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAo49L-DNv_UVk2v1StCzCwR6qPTiHtmvE',
    appId: '1:545721613351:ios:e5da37790c8bbbe04d6202',
    messagingSenderId: '545721613351',
    projectId: 'schedule-up-deejyd',
    storageBucket: 'schedule-up-deejyd.appspot.com',
    iosBundleId: 'com.example.superschedule',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAo49L-DNv_UVk2v1StCzCwR6qPTiHtmvE',
    appId: '1:545721613351:ios:c85476f175a308cf4d6202',
    messagingSenderId: '545721613351',
    projectId: 'schedule-up-deejyd',
    storageBucket: 'schedule-up-deejyd.appspot.com',
    iosBundleId: 'com.example.superschedule.RunnerTests',
  );
}
